### PR TITLE
First revision of a technote

### PR DESCRIPTION
**Pull request by andy-slac**

### CODE REVIEW

**Comment by ktlim** [comment]
Sorry it has taken so long to review this, but I wanted to think about this complex system.

I am worried that not enough consideration has been given to pushing back against the complexity of the underlying database usage.  For example, do we really need the flexibility of mix-and-match managers for each domain, or can the valid sets be given a total order spanning all the domains?  Within individual domains, can we state that new manager implementations will always replace old ones, so that there's no reason to maintain independent migration branches for each?  Even if not, can we have different managers name the tables they manage differently to simplify maintenance and migration from one to another?  If we can't have purely linear migration history, what would we have to change in order to enable standard alembic branch merges?  (It's not clear to me why a branch merge cannot work for int-1.0.0 to uuid-1.0.0; isn't this similar to the "add shopping cart table" example except with a different variant of the same table?)  Instead of creating `alembic_version` from `butler_attributes`, can we eliminate the latter and derive its information from the former?

I am especially worried about the "one-shot" mechanism.  "Tricking" the tool in this way seems ripe for future breakage and incompatibility.  Again, if our database usage is incompatible with standard tools, perhaps it's the usage that needs to change rather than adding more tool complexity.

If we do need this system, including the additional commands, I think they should be implemented as another level of subcommand (`butler migrate add-tree`, `butler migrate show-history`, etc.) rather than a large set of top-level subcommands that will confuse users.  I think this still applies even if the additional commands only show up when an administrator sets up `daf_butler_migrate`.

**Comment by TallJimbo** [comment]
In case Andy sees 

> the flexibility of mix-and-match managers for each domain

as a requirement coming from me, my $0.02 is that _one_ linear migration history would indeed impose constraints on our flexibility that seem risky - that basically assumes that we can pick one butler configuration that will work well in all contexts.  But a small number of independent linear migration histories (1 or 2 now, perhaps an all-time max of about 10) seems quite viable.  Even better if we could in fact do a bit of branching/merging between them using the alembic functionality designed for that.

**Comment by andy-slac** [comment]
I would indeed prefer to have a linear history and a single branch but this is not how our software is structured already. There is a freedom in choosing manager classes in butler configuration and as long as we have that freedom we will end up in a situation when migration between different manager classes is necessary. Manager classes for the same manager type are exclusive, the database presently cannot have schema for more than one class. It's not only table names but mostly references from other tables (in other managers) that make it impractical to try to support that. 

Using alembic merge mechanism cannot work for the reason that manager classes are exclusive. To merge two branches they both need to be in the database and in out case it is not possible. And merging is not even the right thing at logical level, I have no idea what you want to merge if schema of two managers is incompatible. If you want to switch from one manager to a different one it is more or less what "git checkout" does when you switch between branches. Unfortunately alembic does not support that sort of migration so I had to do some dirty tricks to achieve the effect similar to checkout.

I tried to avoid using `alembic_version` to only rely on `butler_attributes` but that is not possible at present. `alembic_version` is deeply integrated into alembic, potentially we could try to add some abstraction layer to alembic but that would need convincing alembic maintainer to accept our PR (and someone spending some effort to make this PR).

**Comment by ktlim** [comment]
The point about linearity is that we could try to place a new manager implementation's migrations entirely after the previous implementation as well as treating the entire database schema across all managers as a single unit.  Yes, this restricts the combination of manager implementation versions that are legal, but that may not be too much of a price to pay.

I wasn't saying to rely only on `butler_attributes`; I was saying to try to eliminate it and use only `alembic_version`.

**Comment by andy-slac** [comment]
Sorry, I mis-read your comment on `alembic_version`. It is not very useful to try to replace `butler_attributes`, it can only store revision IDs which are limited to 32 characters. 

As long as two separate implementation exist they both continue to evolve (if only at the level of bug fix) and think there is no reasonable way to define total ordering between multiple versions of different managers.

As an example suppose there is a manager M1 with version 1.0.0 and we then made new manager M2 with version 1.0.0 and declared that M2 "replaces" M1 and their order will be M1(1.0.0) < M2(1.0.0) < M2(1.0.1), etc.; and we build linear history based on that ordering. But suppose that there is one critical database that did not migrate yet to M2 and cannot migrate so we have to make an emergency patch for M1 with version 1.0.1.  Where does this new version fit in the total ordering defined above and how do we define migration if eventually we want to switch from M1(1.0.1) to M2(2.0.0)?

**Comment by andy-slac** [comment]
I updated technote to document `butler migrate` as a separate sub-command. I'll update CLI on my other ticket (DM-30186) to avoid merge conflicts.

**Pull request merged**
